import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

// icons
import { ArrowUpward } from "@mui/icons-material";

// components
import { Button } from "@mui/material";

import Navigation from "../components/navigation";
import Carousel from "../components/carousel";
import About from "../components/about";
import Service from "../components/service";
import Contact from "../components/contact";
import Footer from "../components/footer";

// styles
import theme from "../styles/Theme.module.scss";

const Home: NextPage = () => {
  // scroll position
  const [yOffset, setYOffset] = useState(0);
  // const [scrollPosition, seScrollPosition] = useState({
  //   about: 0,
  //   service: 0,
  //   contact: 0,
  // });

  // restart scroll
  const restartScroll = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // use effect
  useEffect(() => {
    window.addEventListener("scroll", () => setYOffset(window.scrollY));
    return () =>
      window.removeEventListener("scroll", () => setYOffset(window.scrollY));
  }, []);

  return (
    <div>
      <Head>
        <title>Wolfram - Your Trusted Partner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Carousel yOffset={yOffset} />
      <About yOffset={yOffset} />
      <Service yOffset={yOffset} />
      <Contact yOffset={yOffset} />
      <Footer />
      <div className="fixed right-0 bottom-0 inset-x-0 flex justify-end">
        <Button type="button" className={theme.btn2} onClick={restartScroll}>
          <ArrowUpward />
        </Button>
      </div>
    </div>
  );
};

export default Home;
